spring:
  application:
    name: eventsql-benchmarks-app
  threads:
    virtual:
      enabled:
        true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]

events:
  data-sources:
    - url: "${DB_URL:jdbc:postgresql://localhost:5432/events}"
      username: "${DB_USERNAME:events}"
      password: "${DB_PASSWORD:events}"
      connections: 10
#    - url: "${DB_URL:jdbc:postgresql://localhost:5433/events}"
#      username: "${DB_USERNAME:events}"
#      password: "${DB_PASSWORD:events}"
#    - url: "${DB_URL:jdbc:postgresql://localhost:5434/events}"
#      username: "${DB_USERNAME:events}"
#      password: "${DB_PASSWORD:events}"
  account-created-topic:
    name: "account_created"
    partitions: 10
  account-created-topic-dlt:
    name: "${events.account-created-topic.name}_dlt"
    partitions: 10
  account-created-consumers:
    - topic: "${events.account-created-topic.name}"
      partitioned: true
      name: "test-consumer"
